Create SquashFS Image
Change-Id: I6897db7d67a7d9b6f2beb250356a810e7932dada
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>

diff --git a/generate-squashfs b/generate-squashfs
--- a/generate-squashfs
+++ b/generate-squashfs
@@ -7,6 +7,10 @@ Generates a SquashFS image from the PNOR image
 usage: generate-squashfs [OPTION]
 
 Options:
+   -d, --dir <directory>  Specify destination directory. Defaults to /tmp if
+                          invalid or unspecified.
+   -f, --file <file>      Specify destination file. Defaults to pnor.xz.squashfs
+                          if unspecified.
    -h, --help             Display this help text and exit.
 '
 
@@ -32,9 +36,26 @@ declare -a partitions=(
 "OCC"
 )
 
+outdir="/tmp"
+outfile="pnor.xz.squashfs"
+
 while [[ $# -gt 0 ]]; do
   key="$1"
   case $key in
+    -d|--dir)
+      if [ -d "$2" ]; then
+        outdir="$2"
+      else
+        echo "Invalid or no destination directory specified."
+        echo "Using default destination directory ${outdir}."
+        break
+      fi
+      shift 2
+      ;;
+    -f|--file)
+      outfile="$2"
+      shift 2
+      ;;
     -h|--help)
       echo "$help"
       exit
@@ -46,8 +67,19 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
+scratch_dir=`mktemp -d` || exit 1
+
 for partition in "${partitions[@]}"; do
   echo "Reading ${partition}..."
-  pflash_cmd="pflash --partition=${partition} --read=/tmp/${partition}"
+  pflash_cmd="pflash --partition=${partition} --read=${scratch_dir}/${partition}"
   ${pflash_cmd} || exit 1
 done
+
+echo "Creating SquashFS image..."
+
+cd "${scratch_dir}"
+squashfs_cmd="mksquashfs ${partitions[*]} ${outdir}/${outfile}"
+${squashfs_cmd} || exit 1
+
+echo "SquashFS Image at ${outdir}/${outfile}"
+rm -r "${scratch_dir}"
